rustler::atoms! {
    ok,
    error,
    __nil__ = "nil",

    // memory types
    uint8,
    int8,
    uint16,
    int16,
    uint32,
    int32,

    // imported function param/return types
    i32,
    i64,
    f32,
    f64,
    v128,
    extern_ref,
    func_ref,
    caller,

    // import objects
    __fn__ = "fn",
    global,
    memory,
    table,
    params,
    results,
    maximum,
    minimum,
    shared,
    memory64,
    mutability,
    __const__ = "const",
    var,
    __type__ = "type",

    // wasi import options
    resource,
    alias,
    read,
    write,
    create,

    dir_caps,
    file_caps,
    all,
    create_directory,
    create_file,
    filestat_get,
    filestat_set_times,
    link_source,
    link_target,
    open,
    path_filestat_get,
    path_filestat_set_times,
    readdir,
    readlink,
    remove_directory,
    rename_source,
    rename_target,
    symlink,
    unlink_file,
    advise,
    allocate,
    datasync,
    fdstat_set_flags,
    filestat_set_size,
    poll_readwrite,
    seek,
    sync,
    tell,

    // calls to erlang processes
    returned_function_call,
    invoke_callback,
}
